namespace:
  name: staging

service:
  port: 5111
  type: ClusterIP

image:
  repository: chaberta70/techtrends
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi
